// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "eb439a42-722f-4375-a039-893597cd12a3");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1774963529);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1776106928);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "6c3e73fd-b874-4069-bc7e-48779aec13c8");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1774963526);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1776106923);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 165);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-page-summarization-mvp-treatment-a-callout-badge-rollout-v4:treatment-a-callout-badge");
user_pref("browser.newtabpage.activity-stream.impressionId", "{c9c39446-f593-423b-938d-28785d02960a}");
user_pref("browser.newtabpage.activity-stream.unifiedAds.ohttp.enabled", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.trainhopAddon.version", "151.2.20260328.211913");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.profiles.enabled", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1776106926954");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1776128526954");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20260323182030");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20260323182030");
user_pref("browser.startup.homepage_override.mstone", "149.0");
user_pref("browser.startup.lastColdStartupCheck", 1776106928);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbarbuttons.introduced.sidebar-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"sidebar-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1774963);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "4f5a7c78-7644-4dab-b75d-344bd89d8f97");
user_pref("datareporting.dau.cachedUsageProfileID", "e741709a-2b63-4730-a65b-a21075495a40");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "149.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "afc03ba6727c494da2de7a1b961ba040");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260323182030");
user_pref("extensions.lastAppVersion", "149.0");
user_pref("extensions.lastPlatformVersion", "149.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"d8425c70-0aca-4fb8-b540-c8f7db03d5d9\",\"formautofill@mozilla.org\":\"b014d33f-b023-408c-b2c6-696b72004a0a\",\"ipp-activator@mozilla.com\":\"298815bd-6afe-45ae-80fa-fd37f8de6fb9\",\"pictureinpicture@mozilla.org\":\"14b94072-44c0-4ceb-b185-d07b474b28b3\",\"addons-search-detection@mozilla.com\":\"51b6a3b0-6e49-495f-b7a4-fba311d79def\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"e0d4f193-124a-4195-b27f-bca55afa608f\",\"default-theme@mozilla.org\":\"1f4ad87e-751d-4585-8fa4-1d97b33b6e00\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "beade81e-c0cb-4f0a-a72d-6d3d36f1ff1a");
user_pref("nimbus.profilesdatastoreservice.read.enabled", true);
user_pref("nimbus.profilesdatastoreservice.sync.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherWidth\":0,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.main.tools", "aichat,syncedtabs,history,bookmarks");
user_pref("sidebar.nimbus", "upgraded-sidebar-rollout-without-messaging:rollout-treatment");
user_pref("sidebar.notification.badge.aichat", true);
user_pref("sidebar.revamp", true);
user_pref("sidebar.revamp.defaultLauncherVisible", false);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.firefoxRelay.showToAllBrowsers", true);
user_pref("telemetry.fog.init_on_shutdown", false);
user_pref("toolkit.profiles.storeID", "e2c33bf1");
user_pref("toolkit.startup.last_success", 1776106922);
user_pref("toolkit.telemetry.cachedClientID", "f5de7cc3-c816-4b56-b5c4-33b7692d8b61");
user_pref("toolkit.telemetry.cachedProfileGroupID", "24369f19-0e2c-4167-a50e-be0107df285d");
user_pref("toolkit.telemetry.previousBuildID", "20260323182030");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.user_characteristics_ping.uuid", "{e4482923-e8c9-4849-b8cf-a9a371a88f57}");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
